<a href="https://colab.research.google.com/github/ruchithapatha/Deep-Learning-Projects/blob/main/Mail_spam_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install nltk

In [ ]:
import nltk
import pandas as pd
import numpy as np

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
dt=pd.read_csv("SpamDetectionData.csv",encoding='windows-1252')

In [ ]:
dt.head(7)

type                                               text
0  Spam  <p>But could then once pomp to nor that glee g...
1  Spam  <p>His honeyed and land vile are so and native...
2  Spam  <p>Tear womans his was by had tis her eremites...
3  Spam  <p>The that and land. Cell shun blazon passion...
4  Spam  <p>Sing aught through partings things was sacr...
5  Spam  <p>He den blazon would did prose to he deigned...
6  Spam  <p>In land monastic had sadness will. Found no...

In [ ]:
dt['spam']=dt['type'].map({'Spam':1,'Ham':0}).astype(int)

In [ ]:
dt.head()

type                                               text  spam
0  Spam  <p>But could then once pomp to nor that glee g...     1
1  Spam  <p>His honeyed and land vile are so and native...     1
2  Spam  <p>Tear womans his was by had tis her eremites...     1
3  Spam  <p>The that and land. Cell shun blazon passion...     1
4  Spam  <p>Sing aught through partings things was sacr...     1

In [ ]:
dt.shape

(2100, 3)

In [ ]:
dt.dropna

<bound method DataFrame.dropna of       type                                               text  spam
0     Spam  <p>But could then once pomp to nor that glee g...     1
1     Spam  <p>His honeyed and land vile are so and native...     1
2     Spam  <p>Tear womans his was by had tis her eremites...     1
3     Spam  <p>The that and land. Cell shun blazon passion...     1
4     Spam  <p>Sing aught through partings things was sacr...     1
...    ...                                                ...   ...
2095   Ham  <p>Distant pondered me sought so there perched...     0
2096  Spam  <p>Relief flee not and. Oh will shamed mine by...     1
2097   Ham  <p>Gloated just the shrieked lost morrow in my...     0
2098  Spam  <p>Aye girls had plain the deem to a. At monas...     1
2099   Ham  <p>Above nevermore nothing no and chamber soul...     0

[2100 rows x 3 columns]>

In [ ]:
dt.drop_duplicates

<bound method DataFrame.drop_duplicates of       type                                               text  spam
0     Spam  <p>But could then once pomp to nor that glee g...     1
1     Spam  <p>His honeyed and land vile are so and native...     1
2     Spam  <p>Tear womans his was by had tis her eremites...     1
3     Spam  <p>The that and land. Cell shun blazon passion...     1
4     Spam  <p>Sing aught through partings things was sacr...     1
...    ...                                                ...   ...
2095   Ham  <p>Distant pondered me sought so there perched...     0
2096  Spam  <p>Relief flee not and. Oh will shamed mine by...     1
2097   Ham  <p>Gloated just the shrieked lost morrow in my...     0
2098  Spam  <p>Aye girls had plain the deem to a. At monas...     1
2099   Ham  <p>Above nevermore nothing no and chamber soul...     0

[2100 rows x 3 columns]>

In [ ]:
c=len(dt.columns)
print("No.of columns:",c)
for col in dt.columns:
  print(col)

No.of columns: 3
type
text
spam


In [ ]:
l=len(dt['type'])
print("No.of rows:",l)

No.of rows: 2100


In [ ]:
dt['text'][4]

'<p>Sing aught through partings things was sacred knew did not passion for but prose. Since will none sadness who lines feel to given but my to made seemed low none such all and. Of for delight and childe was carnal childe wight her old in passion awake might whateer. Deem awake amiss was heart had longdeserted. Eremites him low he. Cared fly in who one. Despair the weary the lowly which grief say harold sought. The deeds he said noontide and eremites most long worse yes. Harold revellers partings their. As in and. Of harold and sing of he nor. The his soul other forgot gathered a sick.</p><p>Most if blast on nor cheer to drugged to there. Or what fondly woe lineage lurked eremites at and flash felt all the calm. Consecrate this shades thou the few native nor earthly who he though knew yet few or. Name would had the relief deadly say is at. Nor the bidding uses deigned the that within pangs dear happy shamed tear had ancient them take from before. Her was yet such and had apart fame ti

In [ ]:
def tokenizer(text):
  return text.split()
print(tokenizer(dt['text'][4]))  

['<p>Sing', 'aught', 'through', 'partings', 'things', 'was', 'sacred', 'knew', 'did', 'not', 'passion', 'for', 'but', 'prose.', 'Since', 'will', 'none', 'sadness', 'who', 'lines', 'feel', 'to', 'given', 'but', 'my', 'to', 'made', 'seemed', 'low', 'none', 'such', 'all', 'and.', 'Of', 'for', 'delight', 'and', 'childe', 'was', 'carnal', 'childe', 'wight', 'her', 'old', 'in', 'passion', 'awake', 'might', 'whateer.', 'Deem', 'awake', 'amiss', 'was', 'heart', 'had', 'longdeserted.', 'Eremites', 'him', 'low', 'he.', 'Cared', 'fly', 'in', 'who', 'one.', 'Despair', 'the', 'weary', 'the', 'lowly', 'which', 'grief', 'say', 'harold', 'sought.', 'The', 'deeds', 'he', 'said', 'noontide', 'and', 'eremites', 'most', 'long', 'worse', 'yes.', 'Harold', 'revellers', 'partings', 'their.', 'As', 'in', 'and.', 'Of', 'harold', 'and', 'sing', 'of', 'he', 'nor.', 'The', 'his', 'soul', 'other', 'forgot', 'gathered', 'a', 'sick.</p><p>Most', 'if', 'blast', 'on', 'nor', 'cheer', 'to', 'drugged', 'to', 'there.', '

In [ ]:
dt['text']=dt['text'].apply(tokenizer)

In [ ]:
dt.head()

type                                               text  spam
0  Spam  [<p>But, could, then, once, pomp, to, nor, tha...     1
1  Spam  [<p>His, honeyed, and, land, vile, are, so, an...     1
2  Spam  [<p>Tear, womans, his, was, by, had, tis, her,...     1
3  Spam  [<p>The, that, and, land., Cell, shun, blazon,...     1
4  Spam  [<p>Sing, aught, through, partings, things, wa...     1

In [ ]:
from nltk.stem.snowball import SnowballStemmer
porter=SnowballStemmer("english",ignore_stopwords=False)

In [ ]:
def stem_it(text):
  return [porter.stem(word) for word in text]

In [ ]:
dt['text']=dt['text'].apply(stem_it)

In [ ]:
print(stem_it(dt['text'][4]))

['<p>sing', 'aught', 'through', 'part', 'thing', 'was', 'sacr', 'knew', 'did', 'not', 'passion', 'for', 'but', 'prose.', 'sinc', 'will', 'none', 'sad', 'who', 'line', 'feel', 'to', 'given', 'but', 'my', 'to', 'made', 'seem', 'low', 'none', 'such', 'all', 'and.', 'of', 'for', 'delight', 'and', 'child', 'was', 'carnal', 'child', 'wight', 'her', 'old', 'in', 'passion', 'awak', 'might', 'whateer.', 'deem', 'awak', 'amiss', 'was', 'heart', 'had', 'longdeserted.', 'eremit', 'him', 'low', 'he.', 'care', 'fli', 'in', 'who', 'one.', 'despair', 'the', 'weari', 'the', 'lowli', 'which', 'grief', 'say', 'harold', 'sought.', 'the', 'deed', 'he', 'said', 'noontid', 'and', 'eremit', 'most', 'long', 'wor', 'yes.', 'harold', 'revel', 'part', 'their.', 'as', 'in', 'and.', 'of', 'harold', 'and', 'sing', 'of', 'he', 'nor.', 'the', 'his', 'soul', 'other', 'forgot', 'gather', 'a', 'sick.</p><p>most', 'if', 'blast', 'on', 'nor', 'cheer', 'to', 'drug', 'to', 'there.', 'or', 'what', 'fond', 'woe', 'lineag', 'lu

In [ ]:
dt.head()

type                                               text  spam
0  Spam  [<p>but, could, then, onc, pomp, to, nor, that...     1
1  Spam  [<p>his, honey, and, land, vile, are, so, and,...     1
2  Spam  [<p>tear, woman, his, was, by, had, tis, her, ...     1
3  Spam  [<p>the, that, and, land., cell, shun, blazon,...     1
4  Spam  [<p>sing, aught, through, part, thing, was, sa...     1

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [ ]:
def lemmit_it(text):
  return [lemmatizer.lemmatize(word,pos='a') for word in text]

In [ ]:
print(lemmit_it(dt['text'][4]))

['<p>sing', 'aught', 'through', 'part', 'thing', 'was', 'sacr', 'knew', 'did', 'not', 'passion', 'for', 'but', 'prose.', 'sinc', 'will', 'none', 'sad', 'who', 'line', 'feel', 'to', 'given', 'but', 'my', 'to', 'made', 'seem', 'low', 'none', 'such', 'all', 'and.', 'of', 'for', 'delight', 'and', 'child', 'was', 'carnal', 'child', 'wight', 'her', 'old', 'in', 'passion', 'awak', 'might', 'whateer.', 'deem', 'awak', 'amiss', 'was', 'heart', 'had', 'longdeserted.', 'eremit', 'him', 'low', 'he.', 'care', 'fli', 'in', 'who', 'one.', 'despair', 'the', 'weari', 'the', 'lowli', 'which', 'grief', 'say', 'harold', 'sought.', 'the', 'deed', 'he', 'said', 'noontid', 'and', 'eremit', 'most', 'long', 'wors', 'yes.', 'harold', 'revel', 'part', 'their.', 'as', 'in', 'and.', 'of', 'harold', 'and', 'sing', 'of', 'he', 'nor.', 'the', 'his', 'soul', 'other', 'forgot', 'gather', 'a', 'sick.</p><p>most', 'if', 'blast', 'on', 'nor', 'cheer', 'to', 'drug', 'to', 'there.', 'or', 'what', 'fond', 'woe', 'lineag', 'l

In [ ]:
dt.head()

type                                               text  spam
0  Spam  [<p>but, could, then, onc, pomp, to, nor, that...     1
1  Spam  [<p>his, honey, and, land, vile, are, so, and,...     1
2  Spam  [<p>tear, woman, his, was, by, had, tis, her, ...     1
3  Spam  [<p>the, that, and, land., cell, shun, blazon,...     1
4  Spam  [<p>sing, aught, through, part, thing, was, sa...     1

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
stop_words=stopwords.words('english')

In [ ]:
def stop_it(text):
  review=[word for word in text if not word in stop_words]
  return review

In [ ]:
dt['text']=dt['text'].apply(stop_it)

In [ ]:
print(stop_it(dt['text'][4]))

['<p>sing', 'aught', 'part', 'thing', 'sacr', 'knew', 'passion', 'prose.', 'sinc', 'none', 'sad', 'line', 'feel', 'given', 'made', 'seem', 'low', 'none', 'and.', 'delight', 'child', 'carnal', 'child', 'wight', 'old', 'passion', 'awak', 'might', 'whateer.', 'deem', 'awak', 'amiss', 'heart', 'longdeserted.', 'eremit', 'low', 'he.', 'care', 'fli', 'one.', 'despair', 'weari', 'lowli', 'grief', 'say', 'harold', 'sought.', 'deed', 'said', 'noontid', 'eremit', 'long', 'wors', 'yes.', 'harold', 'revel', 'part', 'their.', 'and.', 'harold', 'sing', 'nor.', 'soul', 'forgot', 'gather', 'sick.</p><p>most', 'blast', 'cheer', 'drug', 'there.', 'fond', 'woe', 'lineag', 'lurk', 'eremit', 'flash', 'felt', 'calm.', 'consecr', 'shade', 'thou', 'nativ', 'earth', 'though', 'knew', 'yet', 'or.', 'name', 'would', 'relief', 'dead', 'say', 'at.', 'bid', 'use', 'deign', 'within', 'pang', 'dear', 'happi', 'shame', 'tear', 'ancient', 'take', 'before.', 'yet', 'apart', 'fame', 'time', 'vaunt', 'though', 'but.', 'co

In [ ]:
dt.head()

type                                               text  spam
0  Spam  [<p>but, could, onc, pomp, glee, glorious, dei...     1
1  Spam  [<p>his, honey, land, vile, nativ, ah, ah, lik...     1
2  Spam  [<p>tear, woman, tis, eremit, present, dear, k...     1
3  Spam  [<p>the, land., cell, shun, blazon, passion, u...     1
4  Spam  [<p>sing, aught, part, thing, sacr, knew, pass...     1

In [ ]:
dt['text']=dt['text'].apply(' '.join)
dt.head()

type                                               text  spam
0  Spam  <p>but could onc pomp glee glorious deigned. v...     1
1  Spam  <p>his honey land vile nativ ah ah like flash ...     1
2  Spam  <p>tear woman tis eremit present dear known no...     1
3  Spam  <p>the land. cell shun blazon passion uncouth ...     1
4  Spam  <p>sing aught part thing sacr knew passion pro...     1

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
y=dt.spam.values
x=tfidf.fit_transform(dt['text'])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.3,shuffle=False)

In [ ]:
#create and train Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB().fit(x_train,y_train)

In [ ]:
#print the predictions
print(classifier.predict(x_train))
#print the actual values
print(y_train)

[1 1 1 ... 0 0 0]
[1 1 1 ... 0 0 0]


In [ ]:
#Now let’s see how well our model performed by evaluating the Naive Bayes classifier and the report, confusion matrix & accuracy score.
# Evaluating the model on the training data set
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=classifier.predict(x_train)
print(classification_report(y_train,pred))
print()
print("Confusion matrix:\n",confusion_matrix(y_train,pred))
print("Accuracy:\n",accuracy_score(y_train,pred)*100)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       470
           1       1.00      1.00      1.00      1000

    accuracy                           1.00      1470
   macro avg       1.00      1.00      1.00      1470
weighted avg       1.00      1.00      1.00      1470


Confusion matrix:
 [[ 470    0]
 [   0 1000]]
Accuracy:
 100.0


In [ ]:
#It looks like the model used is 90.21% accurate. 
#Let’s test the model on the test data set (xtest &  ytest) by printing 
#the predicted value, and the actual value to see if the model can accurately 
#classify the email text.

In [ ]:
#print the predictions
print(classifier.predict(x_test))
#print the actual values
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [ ]:
# Evaluating the model on the training data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_test)
print(classification_report(y_test, pred))
print()
print("Confusion Matrix: \n", confusion_matrix(y_test, pred))
print("Accuracy: \n", accuracy_score(y_test, pred)*100)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       587
           1       1.00      1.00      1.00        43

    accuracy                           1.00       630
   macro avg       1.00      1.00      1.00       630
weighted avg       1.00      1.00      1.00       630


Confusion Matrix: 
 [[587   0]
 [  0  43]]
Accuracy: 
 100.0


In [ ]:
#evaluating test data using logistic regession
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print(classification_report(y_test,y_pred))
print()
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
print("Accuracy: \n", accuracy_score(y_test, y_pred)*100)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00       587
           1       1.00      1.00      1.00        43

    accuracy                           1.00       630
   macro avg       1.00      1.00      1.00       630
weighted avg       1.00      1.00      1.00       630


Confusion Matrix: 
 [[587   0]
 [  0  43]]
Accuracy: 
 100.0


In [ ]:
#print the predictions
print(clf.predict(x_test))
#print the actual values
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0
 0 1 0 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 1 1 1 0 1 1 0 1 1
 1 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0